version: '3.7'
services:  
  dockerOracle19c:
    image: ${DOCKER_ORACLE_19_IMAGE:-fabricads/oracle-19c:1.0.0}
    build:
      context: .
    ports:
      - "${DOCKER_ORACLE_19_PORT:-1521}:1521"
    volumes:
      - "${DOCKER_ORACLE_19_VOLUME_INIT_SQL:-./volumes/config/init/sql}:/volumes/init/sql:ro"
    restart: ${DOCKER_ORACLE_19_RESTART:-unless-stopped}
    deploy:
      restart_policy:
        condition: ${DOCKER_ORACLE_19_RESTART_POLICY_CONDITION:-on-failure}
      resources:
          request:          
            memory: ${DOCKER_ORACLE_19_MEMORY_REQUEST:-2096m}
            cpu: ${DOCKER_ORACLE_19_CPU_REQUEST:-1}
          limits:
            memory: ${DOCKER_ORACLE_19_MEMORY_LIMIT:-4096m}
            cpu: ${DOCKER_ORACLE_19_CPU_LIMIT:-2}
