version: '3.9'
services:  
  dockerOracle19c:
    image: ${DOCKER_ORACLE_19_IMAGE:-rhiemer/oracle-19c:1.0.0}
    build:
      context: .
    ports:
      - "${DOCKER_ORACLE_19_PORT:-1521}:1521"
    restart: ${DOCKER_ORACLE_19_RESTART:-unless-stopped}
    deploy:
      restart_policy:
        condition: ${DOCKER_ORACLE_19_RESTART_POLICY_CONDITION:-on-failure}
      resources:
          reservations:       
            memory: "${DOCKER_ORACLE_19_MEMORY_REQUEST:-2096m}"
            cpus: "${DOCKER_ORACLE_19_CPU_REQUEST:-1.0}"
          limits:
            memory: "${DOCKER_ORACLE_19_MEMORY_LIMIT:-4096m}"
            cpus: "${DOCKER_ORACLE_19_CPU_LIMIT:-2.0}"
