#!/bin/bash
 
source $HOME/.bashrc

ORACLE_USER_PASSWORD="${ORACLE_USER_PASSWORD:-$ORACLE_PWD}"
ORACLE_USER_SYSTEM_PASSWORD="${ORACLE_USER_SYSTEM_PASSWORD:-$ORACLE_PWD}"

SQL_PLUS_CREDENCIAIS_ADMIN="$ORACLE_USER_SYSTEM/$ORACLE_USER_SYSTEM_PASSWORD"

SQL_PLUS_CREDENCIAIS_PWD="$ORACLE_USER_SYSTEM/$ORACLE_PWD"
SQL_PLUS_CREDENCIAIS_PWD_SYSDBA="$ORACLE_USER/$ORACLE_PWD as sysdba"

SQL_PLUS_COMMAND_ADMIN="sqlplus -s $ORACLE_USER_SYSTEM/$ORACLE_USER_SYSTEM_PASSWORD"
SQL_PLUS_COMMAND="$SQL_PLUS_COMMAND_ADMIN"
SQL_PLUS_COMMAND_ADMIN_SYSDBA="$SQL_PLUS_COMMAND_ADMIN as sysdba"
SQL_PLUS_COMMAND_ADMIN_SYSOPER="$SQL_PLUS_COMMAND_ADMIN as sysoper"


SQL_PLUS_COMMAND_CREDENCIAIS_SYS="$ORACLE_USER/$ORACLE_USER_PASSWORD"
SQL_PLUS_COMMAND_CREDENCIAIS_SYS_SYSDBA="$SQL_PLUS_COMMAND_CREDENCIAIS_SYS as sysdba"
SQL_PLUS_COMMAND_SYS="sqlplus -s $SQL_PLUS_COMMAND_CREDENCIAIS_SYS"
SQL_PLUS_COMMAND_SYS_SYSDBA="sqlplus -s $SQL_PLUS_COMMAND_CREDENCIAIS_SYS_SYSDBA"

SQL_PLUS_COMMAND_SYS_SYSDBA_WITH_OUT_PASSWORD="sqlplus -s / as sysdba"

SQL_PLUS_COMMAND_PWD="sqlplus -s $SQL_PLUS_CREDENCIAIS_PWD"
SQL_PLUS_COMMAND_PWD_SYSDBA="sqlplus -s $SQL_PLUS_CREDENCIAIS_PWD_SYSDBA"