#!/bin/bash
 
source $HOME/.bashrc

SQL_PLUS_CREDENCIAIS_ADMIN="$ORACLE_USER_SYSTEM/$ORACLE_USER_SYSTEM_PASSWORD"

SQL_PLUS_COMMAND_ADMIN="sqlplus -s $ORACLE_USER_SYSTEM/$ORACLE_USER_SYSTEM_PASSWORD"
SQL_PLUS_COMMAND="$SQL_PLUS_COMMAND_ADMIN"
SQL_PLUS_COMMAND_ADMIN_SYSDBA="$SQL_PLUS_COMMAND_ADMIN as sysdba"
SQL_PLUS_COMMAND_ADMIN_SYSOPER="$SQL_PLUS_COMMAND_ADMIN as sysoper"


SQL_PLUS_COMMAND_SYS="sqlplus -s $ORACLE_USER/$ORACLE_PASSWORD"
SQL_PLUS_COMMAND_SYS_SYSDBA="$SQL_PLUS_COMMAND_ADMIN as sysdba"
SQL_PLUS_COMMAND_SYS_SYSDBA_WITH_OUT_PASSWORD="sqlplus -s / as sysdba"